
info: 
  component: ${spring.application.name} 

---

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
#      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/

graphite:
  host: localhost
  port: 2003
  # we dont have access to graphite
  enabled: false
  
